extra-deps:
- cryptohash-sha256-0.11.100.1
- echo-0.1.3
- ed25519-0.0.5.0
- mintty-0.1.1
resolver: lts-6.27
flags:
  etlas-cabal:
    parsec: true
  etlas:
    parsec: true
  mintty:
    win32-2-5: false
packages:
- etlas-cabal/
- etlas/
- hackage-security/hackage-security
